# Generated by Django 2.1.7 on 2019-04-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fenster', '0003_apt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apt',
            name='fenster',
        ),
        migrations.DeleteModel(
            name='Apt',
        ),
    ]
